# .github/workflows/build_engine_with_internal_streflop_override.yml
# Workflow to build the BAR engine ('spring'), attempting to force
# its internal streflop build into software float mode for ARM64 macOS.

name: Build BAR Engine (Internal Streflop Override ARM64)

# Allow manual triggering from the GitHub Actions UI
on: workflow_dispatch

jobs:
  build:
    name: Build engine with internal streflop override (arm64)
    # Use the latest standard macOS runner
    runs-on: macos-latest

    steps:
      - name: Checkout engine code
        uses: actions/checkout@v4
        # Ensure submodules are checked out if the engine uses them
        # (Check .gitmodules file in the repo)
        # with:
        #   submodules: 'recursive'

      - name: List files in workspace (DEBUG)
        # See what the top-level directory looks like after checkout
        run: ls -la ${{ github.workspace }}
        shell: bash

      # REMOVED: Step to download pre-built streflop artifact is no longer needed.

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake for Engine
        # Attempt to override streflop build mode globally via CMAKE flags
        # This tries to add DSTREFLOP_SOFT and undefine DSTREFLOP_SSE
        # which is normally added by the main CMakeLists.txt.
        run: |
          cmake -S ${{ github.workspace }} -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DENABLE_STREFLOP=ON \ # Keep streflop enabled
            # Pass flags hoping to override the default DSTREFLOP_SSE
            -DCMAKE_C_FLAGS="-DSTREFLOP_SOFT -U DSTREFLOP_SSE" \
            -DCMAKE_CXX_FLAGS="-DSTREFLOP_SOFT -U DSTREFLOP_SSE"
            # Add any other necessary CMake options for the engine build
            # e.g., -DWITH_HEADLESS=ON if needed, check engine build docs
        shell: bash

      - name: Build BAR Engine
        # Build using the specified build directory
        run: |
          cmake --build ./build --config Release -- -j$(sysctl -n hw.ncpu)
        shell: bash

      # No artifact upload needed here unless we want to save the built engine
      # The success/failure of the build step determines the workflow outcome
