# .github/workflows/build_engine_with_internal_streflop_override.yml
# Workflow to build the BAR engine ('spring'), attempting to force
# its internal streflop build into software float mode for ARM64 macOS.
# v8: Added 'submodules: recursive' to checkout step.

name: Build BAR Engine (Checkout Submodules & Internal Streflop Override ARM64)

# Allow manual triggering from the GitHub Actions UI
on: workflow_dispatch

jobs:
  build:
    name: Build engine with internal streflop override (arm64)
    # Use the latest standard macOS runner
    runs-on: macos-latest

    steps:
      - name: Checkout engine code
        uses: actions/checkout@v4
        # Ensure submodules are checked out recursively
        with:
          submodules: 'recursive' # <-- ADDED THIS LINE

      - name: Install Dependencies (Homebrew)
        run: |
          brew update
          brew install sdl2 devil minizip # Added minizip just in case it's not a submodule
        shell: bash

      - name: List files in workspace (DEBUG)
        run: ls -la ${{ github.workspace }}
        shell: bash

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake for Engine
        # Attempt to enable streflop soft mode globally via CMAKE flags
        run: |
          cmake -S ${{ github.workspace }} -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DENABLE_STREFLOP=ON \ # Keep streflop enabled
            # Pass ONLY the SOFT flag
            -DCMAKE_C_FLAGS="-DSTREFLOP_SOFT" \
            -DCMAKE_CXX_FLAGS="-DSTREFLOP_SOFT"
            # Add any other necessary CMake options for the engine build
        env:
           # Help CMake find Homebrew packages
           CMAKE_PREFIX_PATH: /opt/homebrew/opt/sdl2:/opt/homebrew/opt/devil:/opt/homebrew/opt/minizip # Added minizip path
        shell: bash

      - name: Build BAR Engine
        # Build using the specified build directory
        run: |
          cmake --build ./build --config Release -- -j$(sysctl -n hw.ncpu)
        shell: bash

      # No artifact upload needed here unless we want to save the built engine
      # The success/failure of the build step determines the workflow outcome
